<?php

/*
 * TblClienteImpl
 */

class TblClienteMapper {

    const findAll = "SELECT "
                . "a.id_cliente AS idCliente, "
                . "a.rut AS rut, "
                . "a.nombre AS nombre, "
                . "a.direccion AS direccion, "
                . "a.correo AS correo, "
                . "a.telefono AS telefono, "
                . "a.giro AS giro, "
                . "a.comuna AS comuna, "
                . "a.tipo_comprador AS tipoComprador, "
                . "a.id_usuario AS idUsuario, "
                . "a.observacion AS observacion, "
                . "a.bandera_new AS banderaNew, "
                . "a.fecha_ingreso AS fechaIngreso, "
                . "a.activo AS activo, "
                . "a.id_observacion AS idObservacion, "
                . "a.fecha_obs_mod AS fechaObsMod, "
                . "a.credito AS credito, "
                . "a.id_sector AS idSector "
                . "FROM tbl_cliente a "
                . "WHERE 1=1";
    
    const findById = "SELECT "
                . "a.id_cliente AS idCliente, "
                . "a.rut AS rut, "
                . "a.nombre AS nombre, "
                . "a.direccion AS direccion, "
                . "a.correo AS correo, "
                . "a.telefono AS telefono, "
                . "a.giro AS giro, "
                . "a.comuna AS comuna, "
                . "a.tipo_comprador AS tipoComprador, "
                . "a.id_usuario AS idUsuario, "
                . "a.observacion AS observacion, "
                . "a.bandera_new AS banderaNew, "
                . "a.fecha_ingreso AS fechaIngreso, "
                . "a.activo AS activo, "
                . "a.id_observacion AS idObservacion, "
                . "a.fecha_obs_mod AS fechaObsMod, "
                . "a.credito AS credito, "
                . "a.id_sector AS idSector "
                . "FROM tbl_cliente a "
                . "WHERE 1=1 AND id = :id";

    const save = "INSERT INTO tbl_cliente ("
                . "id_cliente, "
                . "rut, "
                . "nombre, "
                . "direccion, "
                . "correo, "
                . "telefono, "
                . "giro, "
                . "comuna, "
                . "tipo_comprador, "
                . "id_usuario, "
                . "observacion, "
                . "bandera_new, "
                . "fecha_ingreso, "
                . "activo, "
                . "id_observacion, "
                . "fecha_obs_mod, "
                . "credito, "
                . "id_sector "
                . ") VALUES ("
                . ":idCliente, "
                . ":rut, "
                . ":nombre, "
                . ":direccion, "
                . ":correo, "
                . ":telefono, "
                . ":giro, "
                . ":comuna, "
                . ":tipoComprador, "
                . ":idUsuario, "
                . ":observacion, "
                . ":banderaNew, "
                . ":fechaIngreso, "
                . ":activo, "
                . ":idObservacion, "
                . ":fechaObsMod, "
                . ":credito, "
                . ":idSector "
                . ") ON DUPLICATE KEY UPDATE "
                . "id_cliente = :idCliente, "
                . "rut = :rut, "
                . "nombre = :nombre, "
                . "direccion = :direccion, "
                . "correo = :correo, "
                . "telefono = :telefono, "
                . "giro = :giro, "
                . "comuna = :comuna, "
                . "tipo_comprador = :tipoComprador, "
                . "id_usuario = :idUsuario, "
                . "observacion = :observacion, "
                . "bandera_new = :banderaNew, "
                . "fecha_ingreso = :fechaIngreso, "
                . "activo = :activo, "
                . "id_observacion = :idObservacion, "
                . "fecha_obs_mod = :fechaObsMod, "
                . "credito = :credito, "
                . "id_sector = :idSector "
                . "";

    const existsById = "SELECT "
                . "a.id_cliente AS idCliente, "
                . "a.rut AS rut, "
                . "a.nombre AS nombre, "
                . "a.direccion AS direccion, "
                . "a.correo AS correo, "
                . "a.telefono AS telefono, "
                . "a.giro AS giro, "
                . "a.comuna AS comuna, "
                . "a.tipo_comprador AS tipoComprador, "
                . "a.id_usuario AS idUsuario, "
                . "a.observacion AS observacion, "
                . "a.bandera_new AS banderaNew, "
                . "a.fecha_ingreso AS fechaIngreso, "
                . "a.activo AS activo, "
                . "a.id_observacion AS idObservacion, "
                . "a.fecha_obs_mod AS fechaObsMod, "
                . "a.credito AS credito, "
                . "a.id_sector AS idSector "
                . "FROM tbl_cliente a "
                . "WHERE 1=1 AND id = :id";

    
}

?>